---
driver:
  name: vagrant

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_chef_for_busser: false
  require_ruby_for_busser: true
  ansible_verbosity: 2
  ansible_verbose: true
  requirements_path: requirements-test.txt

platforms:
  - name: ubuntu-14.04

suites:
  - name: default

verifier:
  ruby_bindir: '/usr/bin'
